version: 2.1
jobs:
    build:
        docker:
            - image: circleci/python:latest
        steps:
            - checkout  # checkout source code to working directory
            - run:
                name: install dependencies
                command: |
                    python -m virtualenv venv
                    pip install --no-cache-dir -r requirements.txt
            - run: pytest
