version: 2.1
jobs:
    build:
        docker:
            - image: circleci/python:latest
        steps:
            - checkout  # checkout source code to working directory
            - run: pip install --no-cache-dir -r requirements.txt
            - run: pytest
